const { ButtonStyle } = require("discord.js");

module.exports = {
    cutDelayMs: 18_000,
    machines: [
        {
            name: "Máy 1",
            emoji: "⚙️",
            style: ButtonStyle.Primary,
        },
        {
            name: "Máy 2",
            emoji: "⚙️",
            style: ButtonStyle.Primary,
        },
        {
            name: "Máy 3",
            emoji: "⚙️",
            style: ButtonStyle.Primary,
        },
        {
            name: "Máy 4",
            emoji: "⚙️",
            style: ButtonStyle.Primary,
        },
        {
            name: "Máy 5",
            emoji: "⚙️",
            style: ButtonStyle.Primary,
        },
    ],

    gems: {
        rac: {
            name: "Rác",
            emoji: "🗑️",
            baseValue: 1,
        },
        cut_mui_mamu: {
            name: "Cứt mũi bám kính",
            emoji: "🐽",
            baseValue: 10,
        },
        da_binh_thuong: {
            name: "Đá Bình Thường",
            emoji: "🪨",
            baseValue: 50,
        },
        xuong_lon: {
            name: "Xương Lợn",
            emoji: "🦴",
            baseValue: 150,
        },
        thach_anh: {
            name: "Thạch Anh",
            emoji: "🧊",
            baseValue: 700,
        },
        ma_nao: {
            name: "Mã Não",
            emoji: "🟠",
            baseValue: 2500,
        },
        ngoc_bich: {
            name: "Ngọc Bích",
            emoji: "💎",
            baseValue: 8000,
        },
        cam_thach: {
            name: "Cẩm Thạch",
            emoji: "🟢",
            baseValue: 18000,
        },
        phi_thuy: {
            name: "Phỉ Thúy",
            emoji: "💠",
            baseValue: 50000,
        },
        hoa_dien_ngoc: {
            name: "Hòa Điền Ngọc",
            emoji: "🔮",
            baseValue: 120000,
        },
        huyet_ngoc: {
            name: "Huyết Ngọc",
            emoji: "🔴",
            baseValue: 300000,
        },
        hac_long_thach: {
            name: "Hắc Long Thạch",
            emoji: "⚫",
            baseValue: 700000,
        },
        de_vuong_luc: {
            name: "Đế Vương Lục",
            emoji: "👑",
            baseValue: 2000000,
        },
        mamu_hoa_thach: {
            name: "Mamu Hóa Thạch",
            emoji: "🐷",
            baseValue: 8000000,
        },
    },

    purityGrades: [
        {
            name: "Phế Phẩm",
            min: 0,
            max: 5,
            multiplier: 0.01,
        },
        {
            name: "Nứt Toác",
            min: 6,
            max: 15,
            multiplier: 0.04,
        },
        {
            name: "Đục",
            min: 16,
            max: 30,
            multiplier: 0.12,
        },
        {
            name: "Hàng Chợ",
            min: 31,
            max: 50,
            multiplier: 0.35,
        },
        {
            name: "Tạm Ổn",
            min: 51,
            max: 70,
            multiplier: 0.8,
        },
        {
            name: "Có Nước",
            min: 71,
            max: 85,
            multiplier: 1.5,
        },
        {
            name: "Cực Phẩm",
            min: 86,
            max: 95,
            multiplier: 3.5,
        },
        {
            name: "Đế Vương",
            min: 96,
            max: 99,
            multiplier: 12,
        },
        {
            name: "Thiên Mệnh",
            min: 100,
            max: 100,
            multiplier: 60,
        },
    ],

    stones: {
        da_lo: {
            name: "Đá Lỏ",
            emoji: "🪨",
            purityBonus: -15,
            gemChances: {
                rac: 50,
                cut_mui_mamu: 25,
                da_binh_thuong: 15,
                xuong_lon: 6,
                thach_anh: 3,
                ma_nao: 0.8,
                ngoc_bich: 0.18,
                cam_thach: 0.015,
                phi_thuy: 0.004,
                hoa_dien_ngoc: 0.001,
                huyet_ngoc: 0,
                hac_long_thach: 0,
                de_vuong_luc: 0,
                mamu_hoa_thach: 0,
            },
        },
        da_cho_Tau: {
            name: "Đá Chợ Tàu",
            emoji: "🪨",
            purityBonus: -10,
            gemChances: {
                rac: 35,
                cut_mui_mamu: 25,
                da_binh_thuong: 20,
                xuong_lon: 10,
                thach_anh: 6,
                ma_nao: 2.5,
                ngoc_bich: 1,
                cam_thach: 0.35,
                phi_thuy: 0.12,
                hoa_dien_ngoc: 0.025,
                huyet_ngoc: 0.004,
                hac_long_thach: 0.001,
                de_vuong_luc: 0,
                mamu_hoa_thach: 0,
            },
        },
        da_thach_anh: {
            name: "Đá Thạch Anh",
            emoji: "🧊",
            purityBonus: -6,
            gemChances: {
                rac: 22,
                cut_mui_mamu: 18,
                da_binh_thuong: 22,
                xuong_lon: 14,
                thach_anh: 14,
                ma_nao: 6,
                ngoc_bich: 2.5,
                cam_thach: 1,
                phi_thuy: 0.35,
                hoa_dien_ngoc: 0.12,
                huyet_ngoc: 0.025,
                hac_long_thach: 0.004,
                de_vuong_luc: 0.001,
                mamu_hoa_thach: 0,
            },
        },
        da_ma_nao: {
            name: "Đá Mã Não",
            emoji: "🪨",
            purityBonus: -3,
            gemChances: {
                rac: 15,
                cut_mui_mamu: 12,
                da_binh_thuong: 18,
                xuong_lon: 15,
                thach_anh: 18,
                ma_nao: 12,
                ngoc_bich: 5.5,
                cam_thach: 2.8,
                phi_thuy: 1.1,
                hoa_dien_ngoc: 0.45,
                huyet_ngoc: 0.12,
                hac_long_thach: 0.025,
                de_vuong_luc: 0.004,
                mamu_hoa_thach: 0.001,
            },
        },
        da_ngoc_bich: {
            name: "Đá Ngọc Bích",
            emoji: "💎",
            purityBonus: 0,
            gemChances: {
                rac: 10,
                cut_mui_mamu: 8,
                da_binh_thuong: 13,
                xuong_lon: 13,
                thach_anh: 19,
                ma_nao: 16,
                ngoc_bich: 11,
                cam_thach: 5.5,
                phi_thuy: 2.5,
                hoa_dien_ngoc: 1.2,
                huyet_ngoc: 0.55,
                hac_long_thach: 0.2,
                de_vuong_luc: 0.045,
                mamu_hoa_thach: 0.005,
            },
        },
        da_phi_thuy: {
            name: "Đá Phỉ Thúy",
            emoji: "💠",
            purityBonus: 4,
            gemChances: {
                rac: 6,
                cut_mui_mamu: 5,
                da_binh_thuong: 9,
                xuong_lon: 10,
                thach_anh: 16,
                ma_nao: 18,
                ngoc_bich: 16,
                cam_thach: 10,
                phi_thuy: 5.5,
                hoa_dien_ngoc: 2.5,
                huyet_ngoc: 1.25,
                hac_long_thach: 0.55,
                de_vuong_luc: 0.17,
                mamu_hoa_thach: 0.03,
            },
        },
        da_hoa_dien: {
            name: "Đá Hòa Điền",
            emoji: "🔮",
            purityBonus: 8,
            gemChances: {
                rac: 3,
                cut_mui_mamu: 3,
                da_binh_thuong: 6,
                xuong_lon: 7,
                thach_anh: 12,
                ma_nao: 16,
                ngoc_bich: 18,
                cam_thach: 14,
                phi_thuy: 10,
                hoa_dien_ngoc: 6,
                huyet_ngoc: 3,
                hac_long_thach: 1.4,
                de_vuong_luc: 0.5,
                mamu_hoa_thach: 0.1,
            },
        },
        da_mamu: {
            name: "Đá Mamu",
            emoji: "🐷",
            purityBonus: 12,
            gemChances: {
                rac: 1,
                cut_mui_mamu: 2,
                da_binh_thuong: 3,
                xuong_lon: 4,
                thach_anh: 7,
                ma_nao: 10,
                ngoc_bich: 14,
                cam_thach: 16,
                phi_thuy: 15,
                hoa_dien_ngoc: 12,
                huyet_ngoc: 8,
                hac_long_thach: 5,
                de_vuong_luc: 2.4,
                mamu_hoa_thach: 0.6,
            },
        },
    },

    perfectPurityChance: 0.002,

    messages: {
        noStone: "❌ Bạn không có đá này trong kho",
        invalidStone: "❌ Loại đá này chưa đổ thạch được",
        notYourSession: "❌ Không phải đá của bạn",
        expired: "❌ Lượt đổ thạch này đã hết hạn",
        exploded: "💥 Máy nổ cái đùng, đá bay màu",
        success: "✅ Cắt đá thành công",
    },
};
