module.exports = [
    {
        id: "choice_thang_28_ngay",
        difficulty: "easy",
        question: "Mỗi năm có bao nhiêu tháng có 28 ngày?",
        choices: ["1 tháng", "2 tháng", "12 tháng", "Tùy năm nhuận"],
        answerIndex: 2,
        reward: { clue: 1, formation: 3, money: [2500, 5000] },
    },
    {
        id: "choice_lay_2_qua",
        difficulty: "easy",
        question: "Có 3 quả táo, bạn lấy đi 2 quả. Hỏi bạn có mấy quả?",
        choices: ["1 quả", "2 quả", "3 quả", "Không quả nào"],
        answerIndex: 1,
        reward: { clue: 1, formation: 3, money: [2500, 5000] },
    },
    {
        id: "choice_nha_nam",
        difficulty: "easy",
        question: "Nhà Nam có 4 anh chị em. Ba người tên Xuân, Hạ, Thu. Người còn lại tên gì?",
        choices: ["Đông", "Hạ", "Nam", "Không biết"],
        answerIndex: 2,
        reward: { clue: 1, formation: 3, money: [2500, 5000] },
    },
    {
        id: "choice_lay_di_cang_lon",
        difficulty: "medium",
        question: "Cái gì càng lấy đi càng lớn?",
        choices: ["Cái túi", "Cái hố", "Cái bàn", "Cái bóng"],
        answerIndex: 1,
        reward: { clue: 2, formation: 5, money: [5000, 9000] },
    },
    {
        id: "choice_lau_cang_ban",
        difficulty: "medium",
        question: "Cái gì càng lau càng bẩn?",
        choices: ["Cái gương", "Cái khăn", "Cái bàn", "Cái ly"],
        answerIndex: 1,
        reward: { clue: 2, formation: 5, money: [5000, 9000] },
    },
    {
        id: "choice_di_khong_chan",
        difficulty: "medium",
        question: "Cái gì không có chân mà vẫn đi?",
        choices: ["Cái ghế", "Đồng hồ", "Cục đá", "Cái nồi"],
        answerIndex: 1,
        reward: { clue: 2, formation: 5, money: [5000, 9000] },
    },
    {
        id: "choice_song_khong_nuoc",
        difficulty: "medium",
        question: "Cái gì có sông, có núi, có thành phố nhưng không có người sống?",
        choices: ["Bản đồ", "Khu rừng", "Bí cảnh", "Cái hang"],
        answerIndex: 0,
        reward: { clue: 2, formation: 5, money: [5000, 9000] },
    },
    {
        id: "choice_cua_mieng",
        difficulty: "medium",
        question: "Cửa gì không khóa nhưng ai cũng phải mở?",
        choices: ["Cửa nhà", "Cửa xe", "Cửa miệng", "Cửa động"],
        answerIndex: 2,
        reward: { clue: 2, formation: 5, money: [5000, 9000] },
    },
    {
        id: "choice_tem",
        difficulty: "hard",
        question: "Cái gì đi khắp nơi nhưng vẫn nằm yên một chỗ?",
        choices: ["Con tem", "Con thuyền", "Con chim", "Cái dép"],
        answerIndex: 0,
        reward: { clue: 3, formation: 8, money: [9000, 15000] },
    },
    {
        id: "choice_ten_ban",
        difficulty: "hard",
        question: "Thứ gì là của bạn nhưng người khác dùng nhiều hơn bạn?",
        choices: ["Tiền", "Tên của bạn", "Áo của bạn", "Nhà của bạn"],
        answerIndex: 1,
        reward: { clue: 3, formation: 8, money: [9000, 15000] },
    },
    {
        id: "choice_bong_toi",
        difficulty: "hard",
        question: "Thứ gì luôn đi theo bạn khi có ánh sáng, nhưng biến mất trong bóng tối?",
        choices: ["Cái bóng", "Linh thú", "Đồng đội", "Gió"],
        answerIndex: 0,
        reward: { clue: 3, formation: 8, money: [9000, 15000] },
    },
    {
        id: "choice_mat_khong_nhin",
        difficulty: "hard",
        question: "Cái gì có mắt nhưng không nhìn thấy?",
        choices: ["Cây kim", "Con cá", "Cái kính", "Mặt trăng"],
        answerIndex: 0,
        reward: { clue: 3, formation: 8, money: [9000, 15000] },
    },
];