const skillTierNames = {
    F: "Phàm Giai Bí Kỹ",
    E: "Hoàng Giai Bí Kỹ",
    D: "Huyền Giai Bí Kỹ",
    C: "Địa Giai Bí Kỹ",
    B: "Thiên Giai Bí Kỹ",
    A: "Thánh Giai Bí Kỹ",
    S: "Mamu Thần Giai Bí Kỹ",
};

const activeSkills = [
    {
        id: "lon_con_huc_bua",
        name: "Lợn Con Húc Bừa",
        emoji: "🐖",
        tier: "F",
        type: "active",
        role: "damage",
        damageMultiplier: 1.1,
        cooldown: 1,
        description: "Gây 110% ATK sát thương.",
    },
    {
        id: "tru_mom_can_ao",
        name: "Trư Mõm Cắn Áo",
        emoji: "🐽",
        tier: "F",
        type: "active",
        role: "debuff",
        damageMultiplier: 0.9,
        atkDown: 0.05,
        duration: 2,
        cooldown: 2,
        description: "Gây 90% ATK, giảm 5% ATK đối thủ trong 2 lượt.",
    },
    {
        id: "heo_lan_kinh_cong",
        name: "Heo Lăn Khinh Công",
        emoji: "💨",
        tier: "F",
        type: "active",
        role: "speed",
        speedUp: 0.08,
        duration: 2,
        cooldown: 3,
        description: "Tăng 8% Speed trong 2 lượt.",
    },
    {
        id: "tru_vuong_tat_yeu",
        name: "Trư Vương Tát Yêu",
        emoji: "👋",
        tier: "E",
        type: "active",
        role: "damage",
        damageMultiplier: 1.3,
        cooldown: 2,
        description: "Gây 130% ATK sát thương.",
    },
    {
        id: "lon_bay_vo_mat",
        name: "Lợn Bay Vỗ Mặt",
        emoji: "🐷",
        tier: "E",
        type: "active",
        role: "control",
        damageMultiplier: 1,
        stunChance: 0.12,
        cooldown: 3,
        description: "Gây 100% ATK, có 12% làm choáng 1 lượt.",
    },
    {
        id: "mamubeo_tho_doc",
        name: "Mamu Béo Thở Độc",
        emoji: "💨",
        tier: "E",
        type: "active",
        role: "dot",
        damageMultiplier: 0.8,
        poisonPercent: 0.05,
        duration: 3,
        cooldown: 3,
        description: "Gây 80% ATK, khiến đối thủ mất máu trong 3 lượt.",
    },
    {
        id: "tru_anh_xung_kich",
        name: "Trư Ảnh Xung Kích",
        emoji: "💥",
        tier: "D",
        type: "active",
        role: "damage",
        damageMultiplier: 1.55,
        cooldown: 2,
        description: "Gây 155% ATK sát thương.",
    },
    {
        id: "bach_tru_pha_giap",
        name: "Bạch Trư Phá Giáp",
        emoji: "🦴",
        tier: "D",
        type: "active",
        role: "armor_break",
        damageMultiplier: 1.2,
        defenseDown: 0.12,
        duration: 2,
        cooldown: 3,
        description: "Gây 120% ATK, giảm 12% Thủ đối thủ trong 2 lượt.",
    },
    {
        id: "heo_rung_say_quyen",
        name: "Heo Rừng Say Quyền",
        emoji: "🍺",
        tier: "D",
        type: "active",
        role: "crit",
        damageMultiplier: 1.2,
        critChanceBonus: 0.2,
        cooldown: 3,
        description: "Gây 120% ATK, cộng thêm 20% tỉ lệ chí mạng cho đòn này.",
    },
    {
        id: "dia_tru_chan_dia",
        name: "Địa Trư Chấn Địa",
        emoji: "🌍",
        tier: "C",
        type: "active",
        role: "control",
        damageMultiplier: 1.45,
        stunChance: 0.2,
        cooldown: 4,
        description: "Gây 145% ATK, có 20% làm choáng 1 lượt.",
    },
    {
        id: "thiet_bi_lon_than",
        name: "Thiết Bì Lợn Thân",
        emoji: "🛡️",
        tier: "C",
        type: "active",
        role: "defense",
        shieldPercent: 0.18,
        duration: 2,
        cooldown: 4,
        description: "Tạo khiên bằng 18% máu tối đa trong 2 lượt.",
    },
    {
        id: "tru_toc_bat_bo",
        name: "Trư Tốc Bát Bộ",
        emoji: "⚡",
        tier: "C",
        type: "active",
        role: "speed",
        speedUp: 0.18,
        dodgeChance: 0.08,
        duration: 2,
        cooldown: 4,
        description: "Tăng 18% Speed và 8% né tránh trong 2 lượt.",
    },
    {
        id: "thien_tru_liet_khong",
        name: "Thiên Trư Liệt Không",
        emoji: "⚡",
        tier: "B",
        type: "active",
        role: "damage",
        damageMultiplier: 1.75,
        defenseIgnore: 0.12,
        cooldown: 4,
        description: "Gây 175% ATK, bỏ qua 12% Thủ đối thủ.",
    },
    {
        id: "cuu_xich_lon_kiem",
        name: "Cửu Xích Lợn Kiếm",
        emoji: "⚔️",
        tier: "B",
        type: "active",
        role: "multi_hit",
        hits: 3,
        damageMultiplier: 0.6,
        cooldown: 4,
        description: "Đánh 3 lần, mỗi lần gây 60% ATK.",
    },
    {
        id: "tru_hon_ap_che",
        name: "Trư Hồn Áp Chế",
        emoji: "👻",
        tier: "B",
        type: "active",
        role: "debuff",
        damageMultiplier: 1.35,
        atkDown: 0.15,
        speedDown: 0.12,
        duration: 2,
        cooldown: 4,
        description:
            "Gây 135% ATK, giảm 15% ATK và 12% Speed đối thủ trong 2 lượt.",
    },
    {
        id: "thanh_tru_phap_tuong",
        name: "Thánh Trư Pháp Tướng",
        emoji: "👑",
        tier: "A",
        type: "active",
        role: "buff",
        atkUp: 0.22,
        defenseUp: 0.15,
        duration: 3,
        cooldown: 6,
        description: "Tăng 22% ATK và 15% Thủ trong 3 lượt.",
    },
    {
        id: "van_lon_quy_tong",
        name: "Vạn Lợn Quy Tông",
        emoji: "🐗",
        tier: "A",
        type: "active",
        role: "damage",
        damageMultiplier: 2.05,
        lifeSteal: 0.1,
        cooldown: 5,
        description: "Gây 205% ATK, hồi máu bằng 10% sát thương gây ra.",
    },
    {
        id: "tru_than_tram_sat",
        name: "Trư Thần Trảm Sát",
        emoji: "🩸",
        tier: "A",
        type: "active",
        role: "execute",
        damageMultiplier: 1.55,
        executeBonusBelowHp: 0.3,
        executeBonusDamage: 0.45,
        cooldown: 5,
        description:
            "Gây 155% ATK. Nếu đối thủ dưới 30% máu, tăng thêm 45% sát thương.",
    },
    {
        id: "mamu_thon_thien_an",
        name: "Mamu Thôn Thiên Ấn",
        emoji: "🐷",
        tier: "S",
        type: "active",
        role: "ultimate_damage",
        damageMultiplier: 2.35,
        defenseIgnore: 0.2,
        cooldown: 7,
        description: "Gây 235% ATK, bỏ qua 20% Thủ đối thủ.",
    },
    {
        id: "van_tru_tran_thien",
        name: "Vạn Trư Trấn Thiên",
        emoji: "🌌",
        tier: "S",
        type: "active",
        role: "control",
        damageMultiplier: 1.75,
        stunChance: 0.25,
        defenseDown: 0.18,
        duration: 2,
        cooldown: 7,
        description: "Gây 175% ATK, 25% làm choáng, giảm 18% Thủ trong 2 lượt.",
    },
];

const passiveSkills = [
    {
        id: "da_day_lon_rung",
        name: "Dạ Dày Lợn Rừng",
        emoji: "🍖",
        tier: "F",
        type: "passive",
        hpBonus: 0.05,
        description: "Tăng 5% Máu.",
    },
    {
        id: "mong_heo_cung",
        name: "Móng Heo Cứng",
        emoji: "🦶",
        tier: "F",
        type: "passive",
        atkBonus: 0.04,
        description: "Tăng 4% ATK.",
    },
    {
        id: "bi_luoi_than_phap",
        name: "Bì Lười Thân Pháp",
        emoji: "🐌",
        tier: "F",
        type: "passive",
        defenseBonus: 0.05,
        speedBonus: -0.03,
        description: "Tăng 5% Thủ nhưng giảm 3% Speed.",
    },
    {
        id: "tru_bi_ho_the",
        name: "Trư Bì Hộ Thể",
        emoji: "🛡️",
        tier: "E",
        type: "passive",
        defenseBonus: 0.08,
        description: "Tăng 8% Thủ.",
    },
    {
        id: "heo_chay_com",
        name: "Heo Chạy Cơm",
        emoji: "💨",
        tier: "E",
        type: "passive",
        speedBonus: 0.08,
        description: "Tăng 8% Speed.",
    },
    {
        id: "lon_khong_so_chet",
        name: "Lợn Không Sợ Chết",
        emoji: "😤",
        tier: "E",
        type: "passive",
        lowHpAtkBonus: 0.15,
        triggerHpBelow: 0.35,
        description: "Khi máu dưới 35%, tăng 15% ATK.",
    },
    {
        id: "cuong_tru_huyet_mach",
        name: "Cuồng Trư Huyết Mạch",
        emoji: "🩸",
        tier: "D",
        type: "passive",
        atkBonus: 0.1,
        hpBonus: 0.05,
        description: "Tăng 10% ATK và 5% Máu.",
    },
    {
        id: "linh_tru_than_the",
        name: "Linh Trư Thân Thể",
        emoji: "✨",
        tier: "D",
        type: "passive",
        hpBonus: 0.12,
        defenseBonus: 0.06,
        description: "Tăng 12% Máu và 6% Thủ.",
    },
    {
        id: "tru_nhanh_nhu_gio",
        name: "Trư Nhanh Như Gió",
        emoji: "🌪️",
        tier: "D",
        type: "passive",
        speedBonus: 0.12,
        dodgeChance: 0.05,
        description: "Tăng 12% Speed và 5% né tránh.",
    },
    {
        id: "dia_tru_bat_diet",
        name: "Địa Trư Bất Diệt",
        emoji: "⛰️",
        tier: "C",
        type: "passive",
        hpBonus: 0.18,
        defenseBonus: 0.1,
        description: "Tăng 18% Máu và 10% Thủ.",
    },
    {
        id: "tru_tam_bat_on",
        name: "Trư Tâm Bất Ổn",
        emoji: "💢",
        tier: "C",
        type: "passive",
        critChanceBonus: 0.12,
        atkBonus: 0.08,
        description: "Tăng 12% crit và 8% ATK.",
    },
    {
        id: "lon_thich_va_cham",
        name: "Lợn Thích Va Chạm",
        emoji: "💥",
        tier: "C",
        type: "passive",
        counterChance: 0.12,
        counterDamageMultiplier: 0.5,
        description: "Có 12% phản đòn, gây lại 50% ATK.",
    },
    {
        id: "thien_tru_chien_y",
        name: "Thiên Trư Chiến Ý",
        emoji: "🔥",
        tier: "B",
        type: "passive",
        atkBonus: 0.18,
        speedBonus: 0.1,
        description: "Tăng 18% ATK và 10% Speed.",
    },
    {
        id: "cuu_chuyen_tru_than",
        name: "Cửu Chuyển Trư Thân",
        emoji: "🔄",
        tier: "B",
        type: "passive",
        hpBonus: 0.22,
        damageReduction: 0.08,
        description: "Tăng 22% Máu, giảm 8% sát thương nhận vào.",
    },
    {
        id: "tru_hon_khong_diet",
        name: "Trư Hồn Không Diệt",
        emoji: "👻",
        tier: "B",
        type: "passive",
        reviveChance: 0.12,
        reviveHpPercent: 0.2,
        oncePerBattle: true,
        description: "Khi chết, có 12% hồi sinh với 20% máu. Một lần mỗi trận.",
    },
    {
        id: "thanh_tru_chi_the",
        name: "Thánh Trư Chi Thể",
        emoji: "👑",
        tier: "A",
        type: "passive",
        hpBonus: 0.25,
        defenseBonus: 0.14,
        damageReduction: 0.08,
        description: "Tăng 25% Máu, 14% Thủ, giảm 8% sát thương nhận vào.",
    },
    {
        id: "tru_de_huyet_no",
        name: "Trư Đế Huyết Nộ",
        emoji: "🩸",
        tier: "A",
        type: "passive",
        atkBonus: 0.12,
        critChanceBonus: 0.1,
        triggerHpBelow: 0.5,
        lowHpAtkBonus: 0.18,
        description:
            "Tăng 12% ATK và 10% crit. Khi máu dưới 50%, tăng thêm 18% ATK.",
    },
    {
        id: "van_tru_than_toc",
        name: "Vạn Trư Thần Tốc",
        emoji: "⚡",
        tier: "A",
        type: "passive",
        speedBonus: 0.28,
        dodgeChance: 0.12,
        description: "Tăng 28% Speed và 12% né tránh.",
    },
    {
        id: "mamu_thanh_the",
        name: "Mamu Thánh Thể",
        emoji: "🐷",
        tier: "S",
        type: "passive",
        hpBonus: 0.35,
        atkBonus: 0.2,
        defenseBonus: 0.2,
        description: "Tăng 35% Máu, 20% ATK và 20% Thủ.",
    },
    {
        id: "bat_tu_tru_than",
        name: "Bất Tử Trư Thần",
        emoji: "♾️",
        tier: "S",
        type: "passive",
        reviveChance: 0.18,
        reviveHpPercent: 0.25,
        oncePerBattle: true,
        description: "Khi chết, có 18% hồi sinh với 25% máu. Một lần mỗi trận.",
    },
    {
        id: "mamu_chua_te_chien_truong",
        name: "Mamu Chúa Tể Chiến Trường",
        emoji: "👑",
        tier: "S",
        type: "passive",
        atkBonus: 0.25,
        speedBonus: 0.15,
        damageReduction: 0.08,
        critChanceBonus: 0.12,
        description:
            "Tăng 25% ATK, 15% Speed, 12% crit và giảm 8% sát thương nhận vào.",
    },
];

module.exports = {
    skillTierNames,
    activeSkills,
    passiveSkills,
};
