module.exports = {
    enabled: true,

    party: {
        minMembers: 2,
        maxMembers: 4,
        lobbyDurationMs: 10 * 60 * 1000,
        actionDurationMs: 60 * 1000,
        graceDurationMs: 25 * 1000,
    },

    cooldown: {
        soloMs: 15 * 60 * 1000,
        partyMs: 15 * 60 * 1000,
        maxRunsPerDay: 7,
        supportRewardRate: 0.1,
    },

    channel: {
        categoryId: "1342861817105481819",
        deleteDelayMs: 10 * 60 * 1000,
        namePrefix: "san-yeu-thu",
    },

    materials: {
        da_yeu_thu: {
            name: "Da Yêu Thú",
            emoji: "🐾",
            rarity: "common",
        },
        xuong_yeu_thu: {
            name: "Xương Yêu Thú",
            emoji: "🦴",
            rarity: "common",
        },
        nanh_yeu_thu: {
            name: "Nanh Yêu Thú",
            emoji: "🦷",
            rarity: "uncommon",
        },
        yeu_dan_thuong: {
            name: "Yêu Đan Thường",
            emoji: "🔮",
            rarity: "uncommon",
        },
        yeu_dan_tinh_anh: {
            name: "Yêu Đan Tinh Anh",
            emoji: "💠",
            rarity: "rare",
        },
        linh_huyet: {
            name: "Linh Huyết",
            emoji: "🩸",
            rarity: "rare",
        },
        yeu_hach: {
            name: "Yêu Hạch",
            emoji: "💎",
            rarity: "epic",
        },
    },

    beasts: [
        {
            id: "tru_yeu",
            name: "Trư Yêu",
            emoji: "🐗",
            tierName: "Yêu thú thường",
            level: 1,
            soloWeight: 36,
            partyWeight: 24,
            maxTurns: 4,
            hpMultiplier: 0.82,
            damageMultiplier: 0.8,
            rewardMultiplier: 1,
            materials: [
                { id: "da_yeu_thu", weight: 42, min: 1, max: 2 },
                { id: "xuong_yeu_thu", weight: 34, min: 1, max: 1 },
                { id: "yeu_dan_thuong", weight: 12, min: 1, max: 1 },
            ],
        },
        {
            id: "hac_lang_yeu",
            name: "Hắc Lang Yêu",
            emoji: "🐺",
            tierName: "Yêu thú tinh anh",
            level: 2,
            soloWeight: 31,
            partyWeight: 33,
            maxTurns: 4,
            hpMultiplier: 1,
            damageMultiplier: 1,
            rewardMultiplier: 1.12,
            materials: [
                { id: "da_yeu_thu", weight: 32, min: 1, max: 2 },
                { id: "nanh_yeu_thu", weight: 26, min: 1, max: 2 },
                { id: "yeu_dan_thuong", weight: 20, min: 1, max: 1 },
                { id: "linh_huyet", weight: 6, min: 1, max: 1 },
            ],
        },
        {
            id: "xich_lan_xa",
            name: "Xích Lân Xà",
            emoji: "🐍",
            tierName: "Yêu thú thủ lĩnh",
            level: 3,
            soloWeight: 21,
            partyWeight: 27,
            maxTurns: 4,
            hpMultiplier: 1.08,
            damageMultiplier: 1.05,
            rewardMultiplier: 1.28,
            materials: [
                { id: "nanh_yeu_thu", weight: 28, min: 1, max: 2 },
                { id: "yeu_dan_thuong", weight: 24, min: 1, max: 2 },
                { id: "yeu_dan_tinh_anh", weight: 12, min: 1, max: 1 },
                { id: "linh_huyet", weight: 9, min: 1, max: 1 },
            ],
        },
        {
            id: "kim_cang_vien",
            name: "Kim Cang Viên",
            emoji: "🦍",
            tierName: "Yêu thú dị chủng",
            level: 4,
            soloWeight: 8,
            partyWeight: 11,
            maxTurns: 6,
            hpMultiplier: 1.25,
            damageMultiplier: 1.18,
            rewardMultiplier: 1.55,
            materials: [
                { id: "xuong_yeu_thu", weight: 24, min: 2, max: 3 },
                { id: "yeu_dan_tinh_anh", weight: 18, min: 1, max: 1 },
                { id: "linh_huyet", weight: 16, min: 1, max: 2 },
                { id: "yeu_hach", weight: 4, min: 1, max: 1 },
            ],
        },
        {
            id: "giao_long_non",
            name: "Giao Long Non",
            emoji: "🐉",
            tierName: "Thượng cổ yêu thú non",
            level: 5,
            soloWeight: 2,
            partyWeight: 2,
            maxTurns: 6,
            hpMultiplier: 1.42,
            damageMultiplier: 1.28,
            rewardMultiplier: 1.9,
            materials: [
                { id: "yeu_dan_tinh_anh", weight: 24, min: 1, max: 2 },
                { id: "linh_huyet", weight: 20, min: 1, max: 2 },
                { id: "yeu_hach", weight: 10, min: 1, max: 1 },
            ],
        },
    ],

    mechanics: [
        {
            id: "pounce",
            name: "Yêu thú lao thẳng",
            hint: "Yêu thú hạ thấp thân, móng vuốt cào mạnh xuống đất. Nó sắp lao thẳng vào đội hình.",
            roles: ["guard", "attack"],
            soloRole: "guard",
        },
        {
            id: "weak_spot",
            name: "Lộ điểm yếu",
            hint: "Một khe hở chớp nhoáng hiện ra dưới lớp yêu khí. Nếu bỏ lỡ, nó sẽ khép lại ngay.",
            roles: ["explore", "attack"],
            soloRole: "attack",
        },
        {
            id: "poison_mist",
            name: "Độc vụ che mắt",
            hint: "Sương độc lan ra, bóng yêu thú mờ dần. Đánh bừa lúc này rất dễ hụt nhịp.",
            roles: ["explore", "support"],
            soloRole: "explore",
        },
        {
            id: "rage",
            name: "Yêu khí bạo động",
            hint: "Yêu khí quanh nó bạo động dữ dội. Đội hình cần ổn định trước khi phản công.",
            roles: ["guard", "support", "attack"],
            soloRole: "support",
        },
        {
            id: "feint",
            name: "Hư chiêu dụ đòn",
            hint: "Nó cố tình để lộ sơ hở quá rõ. Có vẻ đây là bẫy phản kích.",
            roles: ["explore", "guard"],
            soloRole: "explore",
        },
    ],

    rewards: {
        soloMoneyMin: 8000,
        soloMoneyMax: 28000,
        partyMoneyMin: 10000,
        partyMoneyMax: 35000,
        partyBonusMultiplier: 1.06,
        mvpMoneyMin: 3000,
        mvpMoneyMax: 10000,
    },
};
